name: Angela J. Zhu
favicon: null
layout_spectrum: 0.09728030487895012
typography_spectrum: 0.5598506038077176
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.0742659333627671
  lightness: 0.19178890506736934
  saturation: 0.5577224148437381
  rhythmicContrast: 0.06529071996919811
purpose: []
